name: dotnet

on:
  push:
    branches:
      - main
      - test
      - test2
  pull_request:
    branches:
      - main
      - test
      - test2
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dotnet tools
      run: dotnet tool restore
      
    - name: Restore project dependencies
      run: dotnet restore

    - name: Install Roslynator globally
      run: dotnet tool install -g roslynator.dotnet.cli # Installs Roslynator globally

    - name: Set PATH for Roslynator
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_ENV

    - name: Check Roslynator Installation
      run: dotnet tool list -g

    - name: Build project
      run: dotnet build # Builds the project

    - name: List tools directory
      run: dir $HOME\.dotnet\tools # Verify if Roslynator is in the tools directory

    - name: Run Roslynator analysis
      run: roslynator analyze './Monopost.sln' # Run analysis using Roslynator directly

    env:
      DOTNET_CLI_HOME: ${{ github.workspace }}/temp # Needed for globally installed tools
