name: dotnet

on:
  push:
    branches:
      - main
      - test
      - test2 # Added test2 branch
  pull_request:
    branches:
      - main
      - test
      - test2 # Added test2 branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dotnet tools
      run: dotnet tool restore # Installs local tools specified in dotnet-tools.json

    - name: Restore project dependencies
      run: dotnet restore # Restores the project dependencies

    - name: Install Roslynator globally
      run: dotnet tool install -g roslynator.dotnet.cli # Installs Roslynator globally

    - name: Build project
      run: dotnet build # Builds the project

    - name: Run Roslynator analysis
      run: roslynator analyze ./Monopost.sln # Adjust the path if needed for your solution

    env:
      DOTNET_CLI_HOME: ${{ runner.temp }} # Needed for globally installed tools