name: dotnet

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dotnet tools
      run: dotnet tool restore # Installs local tools specified in dotnet-tools.json

    - name: Restore project dependencies
      run: dotnet restore # Restores the project dependencies

    - name: Build project
      run: dotnet build # Builds the project