name: dotnet

on:
  push:
    branches:
      - main
      - test
      - test2
  pull_request:
    branches:
      - main
      - test
      - test2
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Create tool manifest
      run: dotnet new tool-manifest # Creates a new tool manifest if not present

    - name: Install Roslynator locally
      run: dotnet tool install roslynator.dotnet.cli # Installs Roslynator locally

    - name: Restore dotnet tools
      run: dotnet tool restore # Restores tools specified in the manifest

    - name: Restore project dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build # Builds the project

    - name: Run Roslynator analysis
      run: & "$HOME/.dotnet/tools/roslynator" analyze Monopost.sln # Use PowerShell syntax to invoke Roslynator

    env:
      DOTNET_CLI_HOME: ${{ github.workspace }}/temp # Needed for globally installed tools
